DROP DATABASE IS EXISTS pugs_db;
CREATE DATABASE pugs_db;

USE pugs_db;

CREATE TABLE petPug (
    id INT(11) AUTO_INCREMENT NOT NULL,
    pugName VARCHAR(255),
    didpet BOOLEAN DEFAULT FALSE,
    imgID VARCHAR(5) NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);